
server:
  port: 8081

spring:
  application:
    name: order-service
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        orderCreated-out-0:
          destination: orders.exchange
          content-type: application/json

  datasource:
    url: jdbc:h2:mem:ordersdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
